---
- name: (Debian) Include os_family vars
  include_vars: Debian.yml
  when: ansible_os_family == "Debian"

- name: (RedHat 8) Include os_family vars
  include_vars: "RedHat-{{ ansible_distribution_major_version }}.yml"
  vars:
    versions: ["8"]
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version in versions

- name: (Ubuntu 16.04) Handle errata
  set_fact:
    mysql_daemon: mysql
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "16.04"

- name: (Ubuntu 20.04) Handle errata
  set_fact:
    mysql_packages: "{{ mysql_packages | difference(['python-pymysql']) }}"
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "20.04"

- name: Check required MySQL variables (strings)
  fail:
    msg: |
      Invalid value for variable for '{{ item }}': {{ lookup('vars', item) }}

      Supported types  : String
      Supported values : Any non-null string
  when: >-
    lookup('vars', item) is not string
    or lookup('vars', item) == 0
  with_items: "{{ mysql_required_strings }}"

- name: Check variable 'systemd_restart_setting'
  fail:
    msg: |
      Invalid value for variable 'systemd_restart_setting': '{{ systemd_restart_setting }}'

      Supported types  : String
      Supported values : "no", "on-success", "on-failure", "on-abnormal",
                         "on-watchdog", "on-abort", "always"
  failed_when: >-
    systemd_restart_setting not in
    ['no', 'on-success', 'on-failure', 'on-abnormal',
    'on-watchdog', 'on-abort', 'always']
    or systemd_restart_setting is not string
    or systemd_restart_setting == 0
  when: >-
    (mysql_systemd_restart is defined
    and mysql_systemd_restart)
    or (systemd_restart is defined
    and systemd_restart)
